mcore_ = moduleCreate('core', 'base', '', '')

module_connected = mcore_:newType('module_connected')
server_connected = mcore_:newType('server_connected')
module_component = mcore_:newType('module_component')
module_type = mcore_:newType('module_type')
server_type = mcore_:newType('server_type')
local_state = mcore_:newType('local_state')

module_connected:memberAdd(module_type, 'type')
module_connected:memberAdd(net_connection, 'conn')
module_connected:memberAdd(newArray(module_component), 'serving')
module_connected:memberAdd(int, 'port')
module_connected:memberAdd(uint64, 'ID')

server_connected:memberAdd(server_type, 'type')
server_connected:memberAdd(net_connection, 'conn')
server_connected:memberAdd(int, 'port')
server_connected:memberAdd(int, 'client_count')
server_connected:memberAdd(uint64, 'id')

module_component:memberAdd(module_type, 'mt', true, true)
module_component:memberAdd(pchar, 'name', true, true)
module_component:memberAdd(bool, 'mirror', true, true)
module_component:memberAdd(sl, 'config')
module_component:memberAdd(module_connected, 'primary')
module_component:memberAdd(module_connected, 'secondary')
module_component:memberAdd(uint64, 'pID')
module_component:memberAdd(uint64, 'sID')
module_component:memberAdd(newArray(server_type), 'st')
mc_update_handler = module_component:functionCreate('update_handler', bool)
mc_update_handler:paramAdd(uint64, 'ID')
mc_update_handler:paramAdd(bool, 'primary')

module_type:memberAdd(pchar, 'name', true, true)
module_type:memberAdd(pchar, 'source')
module_type:memberAdd(mcore_:newBST(module_component, 'module_component_bst', true), 'components')
module_type:functionCreate('component_find', module_component):paramAdd(pchar, 'name')
module_type:memberAdd(newArray(module_connected), 'modules')

server_type:memberAdd(pchar, 'name', true, true)
server_type:memberAdd(pchar, 'source')
server_type:memberAdd(sl, 'config')
server_type:memberAdd(newArray(server_connected), 'servers')
server_type:memberAdd(newArray(module_component), 'requires')

module_type_bst = mcore_:newBST(module_type, 'module_type_bst', true)

local_state:memberAdd(jq, 'jq')
local_state:memberAdd(event_set, 'es')
local_state:memberAdd(delay_set, 'ds')
local_state:memberAdd(uint64, 'nextID')
local_state:memberAdd(module_type_bst, 'module_types')
local_state:functionCreate('module_type_find', module_type):paramAdd(pchar, 'name')
local_state:memberAdd(newArray(server_type), 'server_types')
local_state:memberAdd(net_udp, 'udp')
local_state:memberAdd(bool, 'arePrimary')
local_state:memberAdd(net_connection, 'othercore')
local_state:memberAdd(pchar, 'addrOther')
local_state:memberAdd(uint32, 'heartbeat')
local_state:memberAdd(newArray(uchar), 'cp_script')
local_state:memberAdd(newArray(uchar), 'sp_script')
local_state:memberAdd(newArray(uchar), 'mp_script')


